function convertESXtoQB(text) {
    return text
        // Core ESX to QB conversions
        .replace(/esx:onPlayerDeath/g, 'hospital:server:SetDeathStatus')
        .replace(/esx:playerLoaded/g, 'QBCore:Client:OnPlayerLoaded')
        .replace(/esx:showAdvancedNotification/g, 'QBCore:Notify')
        .replace(/esx:showHelpNotification/g, 'QBCore:Notify')
        .replace(/esx:showNotification/g, 'QBCore:Notify')
        .replace(/ESX.GetPlayerData/g, 'QBCore.Functions.GetPlayerData')
        .replace(/ESX.SetPlayerData/g, 'QBCore.Player:SetPlayerData')
        .replace(/ESX.TriggerServerCallback/g, 'QBCore.Functions.TriggerCallback')

        // Game functions
        .replace(/ESX.Game.DeleteObject/g, 'DeleteEntity')
        .replace(/ESX.Game.DeleteVehicle/g, 'QBCore.Functions.DeleteVehicle')
        .replace(/ESX.Game.GetClosestPed/g, 'QBCore.Functions.GetClosestPed')
        .replace(/ESX.Game.GetClosestPlayer/g, 'QBCore.Functions.GetClosestPlayer')
        .replace(/ESX.Game.GetClosestVehicle/g, 'QBCore.Functions.GetClosestVehicle')
        .replace(/ESX.Game.SetVehicleProperties/g, 'QBCore.Functions.SetVehicleProperties')
        .replace(/ESX.Game.SpawnVehicle/g, 'QBCore.Functions.SpawnVehicle')
        .replace(/ESX.Game.Teleport/g, 'SetEntityCoords and SetEntityHeading')
        .replace(/ESX.GetPlayerFromId/g, 'QBCore.Functions.GetPlayer')
        .replace(/ESX.GetPlayerFromIdentifier/g, 'QBCore.Functions.GetPlayerByCitizenId')
        .replace(/ESX.GetPlayers/g, 'QBCore.Functions.GetPlayers')
        .replace(/ESX.RegisterServerCallback/g, 'QBCore.Functions.CreateCallback')
        .replace(/ESX.RegisterUsableItem/g, 'QBCore.Functions.CreateUseableItem')
        .replace(/ESX.RegisterCommand/g, 'QBCore.Commands.AddCommand')

        // Additional conversions based on code snippets
        .replace(/TriggerEvent\('esx:getSharedObject', function\(obj\) ESX = obj end\)/g, 'TriggerEvent(\'QBCore:GetObject\', function(obj) QBCore = obj end)')
        .replace(/while ESX == nil do/g, 'while QBCore == nil do')
        .replace(/ESX.TriggerServerCallback/g, 'QBCore.Functions.TriggerCallback')
        .replace(/ESX.Game.GetVehicleProperties/g, 'QBCore.Functions.GetVehicleProperties')
        .replace(/ESX.Game.DeleteVehicle/g, 'QBCore.Functions.DeleteVehicle')
        .replace(/ESX.Game.SpawnVehicle/g, 'QBCore.Functions.SpawnVehicle')
        .replace(/ESX.Game.GetClosestVehicle/g, 'QBCore.Functions.GetClosestVehicle')
        .replace(/ESX =\s*nil/g, 'QBCore = nil')
        .replace(/RegisterNetEvent\('esx:playerLoaded'\)/g, 'RegisterNetEvent(\'QBCore:Client:OnPlayerLoaded\')')
        .replace(/AddEventHandler\('esx:playerLoaded',/g, 'AddEventHandler(\'QBCore:Client:OnPlayerLoaded\',')
        .replace(/RegisterNetEvent\('esx:setJob'\)/g, 'RegisterNetEvent(\'QBCore:Client:OnJobUpdate\')')
        .replace(/AddEventHandler\('esx:setJob',/g, 'AddEventHandler(\'QBCore:Client:OnJobUpdate\',')
        .replace(/RegisterNetEvent\('esx:onPlayerDeath'\)/g, 'RegisterNetEvent(\'QBCore:Client:OnPlayerUnload\')')
        .replace(/AddEventHandler\('esx:onPlayerDeath',/g, 'AddEventHandler(\'QBCore:Client:OnPlayerUnload\',')
        .replace(/ESX.Game.GetClosestPlayer\(\)/g, 'QBCore.Functions.GetClosestPlayer()')
        .replace(/ESX.UI.Menu.Open/g, 'QBCore.UI.Menu.Open')
        .replace(/ESX.UI.Menu.CloseAll\(\)/g, 'QBCore.UI.Menu.CloseAll()')
        .replace(/xPlayer.getInventoryItem/g, 'xPlayer.Functions.GetItemByName')
        .replace(/RegisterNetEvent\('esx:setJob'\)/g, 'RegisterNetEvent(\'QBCore:Client:OnJobUpdate\')')
        .replace(/AddEventHandler\('esx:setJob', function\(job\)/g, 'AddEventHandler(\'QBCore:Client:OnJobUpdate\', function(job)')
        .replace(/xPlayer.removeAccountMoney\('bank', amount\)/g, 'ply.Functions.AddMoney(\'bank\', amount, "Bank deposit")')
        .replace(/xPlayer.addMoney\(amount\)/g, 'ply.Functions.RemoveMoney(\'cash\', amount, "Bank deposit")')
        .replace(/xPlayer.getAccount\('bank'\).money/g, 'ply.PlayerData.money["bank"]')
        .replace(/xPlayer.removeInventoryItem/g, 'xPlayer.Functions.RemoveItem')
        .replace(/xPlayer.addInventoryItem/g, 'xPlayer.Functions.AddItem')
        .replace(/ESX.GetPlayerFromId/g, 'QBCore.Functions.GetPlayer')
        .replace(/ESX.GetPlayerFromIdentifier/g, 'QBCore.Functions.GetPlayerByCitizenId')
        .replace(/ESX.Math.Trim\(value\)/g, 'QBCore.Functions.MathTrim')
        .replace(/ESX.GetPlayerData\(\)/g, 'QBCore.Functions.GetPlayerData()')
        .replace(/ESX.RegisterUsableItem\(\)/g, 'QBCore.Functions.CreateUseableItem()')
        .replace(/xPlayer.removeMoney\(money\)/g, 'Player.Functions.RemoveMoney()')
        .replace(/ESX.RegisterServerCallback\(\)/g, 'QBCore.Functions.CreateCallback()')
        .replace(/ESX.TriggerServerCallback\(\)/g, 'QBCore.Functions.TriggerCallback()')
        .replace(/TriggerEvent\('esx:showNotification',/g, 'TriggerEvent(\'QBCore:Notify\',')
        .replace(/AddEventHandler\('esx_/g, 'AddEventHandler(\'qb_')
        .replace(/RegisterNetEvent\('esx_/g, 'RegisterNetEvent(\'qb_')
        .replace(/TriggerServerEvent\('esx_/g, 'TriggerServerEvent(\'qb_')
        .replace(/TriggerCallback\('esx_/g, 'TriggerCallback(\'qb_')
        .replace(/ESX.ShowNotification/g, 'QBCore.Functions.Notify')
        .replace(/ESX.RegisterServerCallback\("system:fetchStatus", function\(source, cb\)/g, 'QBCore.Functions.CreateCallback(\'system:fetchStatus\', function(source, cb)')
        .replace(/local src = source\n\nlocal user = ESX.GetPlayerFromId\(src\)\n\n\n\nlocal fetch = \[\[.*\]\]/g, 'local Player = QBCore.Functions.GetPlayer(source)\n\nif Player then\n     exports[\'ghmattimysql\']:execute(\'SELECT skills FROM players WHERE citizenid = @citizenid\', {\n          [\'@citizenid\'] = Player.PlayerData.citizenid\n     }, function(status)\n          if status ~= nil then\n               cb(json.decode(status))\n          else\n               cb(nil)\n          end\n     end)\nelse\n     cb()\nend')
        .replace(/RegisterCommand /g, 'QBCore.Commands.Add()')
        .replace(/local user = ESX.GetPlayerFromId\(src\)/g, 'local Player = QBCore.Functions.GetPlayer(source)')
        .replace(/["@identifier"] = user.identifier/g, '[@citizenid] = Player.PlayerData.citizenid')
        .replace(/xPlayer.addMoney\(amount\)/g, 'ply.Functions.AddMoney(\'cash\', amount, "Cash deposit")'); // Fix for adding money

}

module.exports = { convertESXtoQB };
