function convertQBtoESX(text) {
    return text
        // Core QB to ESX conversions
        .replace(/hospital:server:SetDeathStatus/g, 'esx:onPlayerDeath')
        .replace(/QBCore:Client:OnPlayerLoaded/g, 'esx:playerLoaded')
        .replace(/QBCore:Notify/g, 'esx:showNotification') // Assume most uses will be for 'showNotification'
        .replace(/QBCore.Functions.GetPlayerData/g, 'ESX.GetPlayerData')
        .replace(/QBCore.Player:SetPlayerData/g, 'ESX.SetPlayerData')
        .replace(/QBCore.Functions.TriggerCallback/g, 'ESX.TriggerServerCallback')

        // Game functions
        .replace(/DeleteEntity/g, 'ESX.Game.DeleteObject')
        .replace(/QBCore.Functions.DeleteVehicle/g, 'ESX.Game.DeleteVehicle')
        .replace(/QBCore.Functions.GetClosestPed/g, 'ESX.Game.GetClosestPed')
        .replace(/QBCore.Functions.GetClosestPlayer/g, 'ESX.Game.GetClosestPlayer')
        .replace(/QBCore.Functions.GetClosestVehicle/g, 'ESX.Game.GetClosestVehicle')
        .replace(/QBCore.Functions.SetVehicleProperties/g, 'ESX.Game.SetVehicleProperties')
        .replace(/QBCore.Functions.SpawnVehicle/g, 'ESX.Game.SpawnVehicle')
        .replace(/SetEntityCoords and SetEntityHeading/g, 'ESX.Game.Teleport')
        .replace(/QBCore.Functions.GetPlayer/g, 'ESX.GetPlayerFromId')
        .replace(/QBCore.Functions.GetPlayerByCitizenId/g, 'ESX.GetPlayerFromIdentifier')
        .replace(/QBCore.Functions.GetPlayers/g, 'ESX.GetPlayers')
        .replace(/QBCore.Functions.CreateCallback/g, 'ESX.RegisterServerCallback')
        .replace(/QBCore.Functions.CreateUseableItem/g, 'ESX.RegisterUsableItem')
        .replace(/QBCore.Commands.AddCommand/g, 'ESX.RegisterCommand')

        // Additional conversions based on code snippets
        .replace(/TriggerEvent\('QBCore:GetObject', function\(obj\) QBCore = obj end\)/g, 'TriggerEvent(\'esx:getSharedObject\', function(obj) ESX = obj end)')
        .replace(/while QBCore == nil do/g, 'while ESX == nil do')
        .replace(/QBCore.Functions.TriggerCallback/g, 'ESX.TriggerServerCallback')
        .replace(/QBCore.Functions.GetVehicleProperties/g, 'ESX.Game.GetVehicleProperties')
        .replace(/QBCore.Functions.DeleteVehicle/g, 'ESX.Game.DeleteVehicle')
        .replace(/QBCore.Functions.SpawnVehicle/g, 'ESX.Game.SpawnVehicle')
        .replace(/QBCore.Functions.GetClosestVehicle/g, 'ESX.Game.GetClosestVehicle')
        .replace(/QBCore =\s*nil/g, 'ESX = nil')
        .replace(/RegisterNetEvent\('QBCore:Client:OnPlayerLoaded'\)/g, 'RegisterNetEvent(\'esx:playerLoaded\')')
        .replace(/AddEventHandler\('QBCore:Client:OnPlayerLoaded',/g, 'AddEventHandler(\'esx:playerLoaded\',')
        .replace(/RegisterNetEvent\('QBCore:Client:OnJobUpdate'\)/g, 'RegisterNetEvent(\'esx:setJob\')')
        .replace(/AddEventHandler\('QBCore:Client:OnJobUpdate',/g, 'AddEventHandler(\'esx:setJob\',')
        .replace(/RegisterNetEvent\('QBCore:Client:OnPlayerUnload'\)/g, 'RegisterNetEvent(\'esx:onPlayerDeath\')')
        .replace(/AddEventHandler\('QBCore:Client:OnPlayerUnload',/g, 'AddEventHandler(\'esx:onPlayerDeath\',')
        .replace(/QBCore.Functions.GetClosestPlayer\(\)/g, 'ESX.Game.GetClosestPlayer()')
        .replace(/QBCore.UI.Menu.Open/g, 'ESX.UI.Menu.Open')
        .replace(/QBCore.UI.Menu.CloseAll\(\)/g, 'ESX.UI.Menu.CloseAll()')
        .replace(/xPlayer.Functions.GetItemByName/g, 'xPlayer.getInventoryItem')
        .replace(/RegisterNetEvent\('QBCore:Client:OnJobUpdate'\)/g, 'RegisterNetEvent(\'esx:setJob\')')
        .replace(/AddEventHandler\('QBCore:Client:OnJobUpdate', function\(job\)/g, 'AddEventHandler(\'esx:setJob\', function(job)')
        .replace(/ply.Functions.AddMoney\('bank', amount, "Bank deposit"\)/g, 'xPlayer.removeAccountMoney(\'bank\', amount)')
        .replace(/ply.Functions.RemoveMoney\('cash', amount, "Bank deposit"\)/g, 'xPlayer.addMoney(amount)')
        .replace(/ply.PlayerData.money\["bank"\]/g, 'xPlayer.getAccount(\'bank\').money')
        .replace(/xPlayer.Functions.RemoveItem/g, 'xPlayer.removeInventoryItem')
        .replace(/xPlayer.Functions.AddItem/g, 'xPlayer.addInventoryItem')
        .replace(/QBCore.Functions.GetPlayer/g, 'ESX.GetPlayerFromId')
        .replace(/QBCore.Functions.GetPlayerByCitizenId/g, 'ESX.GetPlayerFromIdentifier')
        .replace(/QBCore.Functions.MathTrim/g, 'ESX.Math.Trim')
        .replace(/QBCore.Functions.GetPlayerData\(\)/g, 'ESX.GetPlayerData()')
        .replace(/QBCore.Functions.CreateUseableItem\(\)/g, 'ESX.RegisterUsableItem()')
        .replace(/Player.Functions.RemoveMoney\(\)/g, 'xPlayer.removeMoney(money)')
        .replace(/QBCore.Functions.CreateCallback\(\)/g, 'ESX.RegisterServerCallback()')
        .replace(/QBCore.Functions.TriggerCallback\(\)/g, 'ESX.TriggerServerCallback()')
        .replace(/TriggerEvent\('QBCore:Notify',/g, 'TriggerEvent(\'esx:showNotification\',')
        .replace(/AddEventHandler\('qb_/g, 'AddEventHandler(\'esx_')
        .replace(/RegisterNetEvent\('qb_/g, 'RegisterNetEvent(\'esx_')
        .replace(/TriggerServerEvent\('qb_/g, 'TriggerServerEvent(\'esx_')
        .replace(/TriggerCallback\('qb_/g, 'TriggerCallback(\'esx_')
        .replace(/QBCore.Functions.Notify/g, 'ESX.ShowNotification')
        .replace(/QBCore.Functions.CreateCallback\('system:fetchStatus', function\(source, cb\)/g, 'ESX.RegisterServerCallback("system:fetchStatus", function(source, cb)')
        .replace(/local Player = QBCore.Functions.GetPlayer\(source\)\n\nif Player then\n     exports\['ghmattimysql'\]:execute\('SELECT skills FROM players WHERE citizenid = @citizenid', {\n          \['@citizenid'\] = Player.PlayerData.citizenid\n     }, function\(status\)\n          if status ~= nil then\n               cb\(json.decode\(status\)\)\n          else\n               cb\(nil\)\n          end\n     end\)\nelse\n     cb\(\)\nend/g, 'local src = source\n\nlocal user = ESX.GetPlayerFromId(src)\n\n\n\nlocal fetch = [[\n     SELECT\n          skills\n     FROM\n          users\n     WHERE\n          identifier = @identifier\n]]\n\nMySQL.Async.fetchScalar(fetch, {\n     ["@identifier"] = user.identifier\n\n}, function(status)\n     if status ~= nil then\n          cb(json.decode(status))\n     else\n          cb(nil)\n     end\nend)\nend)')
        .replace(/QBCore.Commands.Add\(\)/g, 'RegisterCommand ')
        .replace(/local Player = QBCore.Functions.GetPlayer\(source\)/g, 'local user = ESX.GetPlayerFromId(src)')
        .replace(/['@citizenid'] = Player.PlayerData.citizenid/g, '["@identifier"] = user.identifier')
        .replace(/ply.Functions.AddMoney\('cash', amount, "Cash deposit"\)/g, 'xPlayer.addMoney(amount)'); // Fix for adding money
}

module.exports = { convertQBtoESX };
